# This file is machine-generated - editing it directly is not advised

[[LLVM]]
deps = ["Printf", "Unicode"]
git-tree-sha1 = "f988262deeeb3350f2dbf0b3aff6758c13a2fbd8"
repo-rev = "vc/types"
repo-url = "LLVM"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "1.1.0+"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
